[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.10.0"
indicatif = {version = "0.17.8", features = ["rayon"]}

[profile.release]
codegen-units = 1
lto = "fat"
